spring:
  application:
    name: OAuthDemo
  security:
    oauth2:
        client:
          registration:
            google:
              client-id: **************************************************
              client-secret: ***********************************

